### ISSUE TITLE
out of slice fading of point and orientation layer

### ISSUE THREAD

**Issue by McHaillet** [brisvag/blik#164]
The fading (out of slice) is very useful when going through tomographic slices but is not happening at the same rate for the point and orientation layer. The point size first needs to be increased to size 5 to function as I would expect. @brisvag also mentioned in discussion he needed to fix something about sizes and lengths related to this ;)

@ldjager tagging you here as I thought you might want to follow!

**Comment by brisvag** [comment]
The `out_of_slice` trick is cool but hard to implement sensibly with vectors. It't aslo a bit limited because it forces you to resize objects to "adjust" (as you discovered).

This is one of the reasons I worked on thick slices in napari in the last year; this is not yet out but will be with the next version.

If you want to try out, install the [nightly version](https://github.com/brisvag/blik?tab=readme-ov-file#nightly-build) and you should get a new slider in the main widget which adjusts the thickness of the slice.

**Comment by McHaillet** [comment]
I just tried the slice thickness option and it works great! That for my part fixes the issue :)
